### ISSUE TITLE
Relation with pypi pyslp pure Python3 module

### ISSUE THREAD

**Issue by rchateauneu** [tsmetana/python-libslp#1]
There is a module with the same name, for Python3 only, on pypi:

https://pypi.python.org/pypi/pyslp

Is there any hope to merge the two modules ? It would be fantastic to have a pure Python module, for Python2 and 3 also.

Many thanks

RC

**Comment by tsmetana** [comment]
Hi. There is no relation between "my" pyslp an the one you linked to: that one looks to be fairly new (half a year), mine is a fallout of the OpenLMI project (dead for some 3 years). Also I didn't intend to re-implement SLP in Python but created only bindings to libslp (from [OpenSLP](https://sourceforge.net/projects/openslp/)) and mimic the RFC specification. It's really just one small C file "translating" the function calls.

On the contrary the referenced pypi module is really a complete Python-only implementation of the protocol. It makes no sense trying to merge the two modules IMO.

However thanks for asking: I will try to rename this repository to avoid confusion...
