### ISSUE TITLE
Releasing this package to Pypi

### ISSUE THREAD

**Issue by andy-maier** [tsmetana/python-libslp#2]
Hi,
is there any chance you might want to release python-libslp as a Python package to Pypi? That would make it much more easily consumable for Python programmers.

**Comment by tsmetana** [comment]
Hi. This package was never actually used in any project I originally intended it for so I don't think packagint it it to PyPi makes much sense. If there was an interested in using it for something then maybe.

**Comment by rchateauneu** [comment]
This would definitively of interest for this project https://github.com/rchateauneu/survol I am working on. It would be needed to interact with WBEM servers (https://fr.wikipedia.org/wiki/Web-Based_Enterprise_Management).

Many thanks.

**Comment by mrv96** [comment]
I agree with @rchateauneu. It is the only valid option to use SLP in Python. PySLP library (https://pypi.org/project/pyslp/) is not complete and not totally compliant with SLP standard.

**Comment by rchateauneu** [comment]
By the way it is really great that we still have compatibility with Python 2. Thanks !
